# Generated by Django 3.1 on 2021-08-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(blank=True, max_length=80)),
                ('activation_code', models.CharField(blank=True, max_length=8)),
                ('sex', models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users')),
                ('birthdate', models.DateField(verbose_name='Date of Birth')),
                ('date_join', models.DateField(verbose_name='Date of Register')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
